### ISSUE TITLE
MageSlayer and Take no Prisoners not work with pal-ddraw correctly in Windows XP+, but work right in Windows 98SE

### ISSUE THREAD

**Issue by lighteon** [ayuanx/pal-ddraw#5]
Sry for my bad english. You not understand me, i think.
I have retro config based on Athlon 64/Geforce 3 Ti with windows 98SE and test you wrappers.
And in this games ddraw-pal work in Windows 98SE, but not worked in Windows XP+

**Comment by ayuanx** [comment]
I understand what you mean.

The reason why you think pal-ddraw works in Win98 for this game is because when pal-ddraw detects that current OS already supports the desired color depth, it won't activate itself.

In this case, Win98 already supports 8-bit color and 16-bit color natively, so no wrapper is required and pal-ddraw stays inactive.
